{
 "title": "EventCart Overview",
 "tags": [
  "eventcart",
  "microservices"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "HTTP Request Rate (order-service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"order-service\"}[5m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "HTTP Latency p95 (order-service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"order-service\"}[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "JVM Memory Used (all services)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"}) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  }
 ]
}